# Generated by Django 4.2.7 on 2023-11-08 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free_ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.TextField(max_length=255)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='free_ads.ad')),
            ],
        ),
    ]
